package ApartadoA;

import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Jesús Calvente Ramírez & Victor Moreno Benítez
 */
public class ApartadoA extends javax.swing.JFrame {

    /**
     * Creates new form ApartadoA
     */
    private int numeroAleatorio;

    public ApartadoA() {
        initComponents();
        this.setTitle("Adivina el numero");
        this.setLocationRelativeTo(null);
        numeroAleatorio = (int) ((Math.random() * 100) + 1);
        textIntentos.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAdvina = new javax.swing.JLabel();
        labelSubAdivina = new javax.swing.JLabel();
        labelApuestas = new javax.swing.JLabel();
        textApuesta = new javax.swing.JTextField();
        botonApuesta = new javax.swing.JButton();
        botonRendirse = new javax.swing.JButton();
        labelIntento = new javax.swing.JLabel();
        textIntentos = new javax.swing.JTextField();
        labelInfo = new javax.swing.JLabel();
        textInfo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelAdvina.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        labelAdvina.setForeground(new java.awt.Color(0, 0, 0));
        labelAdvina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelAdvina.setText("Adivina el Numero");
        labelAdvina.setToolTipText("");

        labelSubAdivina.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelSubAdivina.setForeground(new java.awt.Color(0, 0, 0));
        labelSubAdivina.setText("El objetivo del juego es encontrar el numero entre 1 y 100 que ha pensado el ordenador.");
        labelSubAdivina.setToolTipText("");

        labelApuestas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelApuestas.setForeground(new java.awt.Color(0, 0, 0));
        labelApuestas.setText("Tu Apuesta:");

        textApuesta.setBackground(new java.awt.Color(255, 255, 255));
        textApuesta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textApuesta.setForeground(new java.awt.Color(0, 0, 0));

        botonApuesta.setBackground(new java.awt.Color(204, 204, 204));
        botonApuesta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        botonApuesta.setForeground(new java.awt.Color(0, 0, 0));
        botonApuesta.setText("Apuesta");
        botonApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonApuestaActionPerformed(evt);
            }
        });

        botonRendirse.setBackground(new java.awt.Color(204, 204, 204));
        botonRendirse.setForeground(new java.awt.Color(0, 0, 0));
        botonRendirse.setText("Me Rindo");
        botonRendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRendirseActionPerformed(evt);
            }
        });

        labelIntento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelIntento.setForeground(new java.awt.Color(0, 0, 0));
        labelIntento.setText("#-Intentos:");

        textIntentos.setEditable(false);
        textIntentos.setBackground(new java.awt.Color(255, 255, 255));
        textIntentos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textIntentos.setForeground(new java.awt.Color(0, 0, 0));

        labelInfo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelInfo.setForeground(new java.awt.Color(0, 0, 0));
        labelInfo.setText("INFO:");

        textInfo.setEditable(false);
        textInfo.setBackground(new java.awt.Color(255, 255, 255));
        textInfo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textInfo.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pitonisa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(textInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAdvina, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelApuestas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(botonApuesta)
                                .addGap(52, 52, 52)
                                .addComponent(botonRendirse))
                            .addComponent(labelSubAdivina)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelAdvina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSubAdivina, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelApuestas)
                            .addComponent(textApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRendirse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelInfo)
                            .addComponent(textInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton2)))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonApuestaActionPerformed
        // TODO add your handling code here:
        try {
            int numJugador = Integer.valueOf(textApuesta.getText().toString());
            if (numJugador > 0 && numJugador < 101) {
                if (numJugador == numeroAleatorio) {
                    JOptionPane.showMessageDialog(this, "Felicidades has ganado a la maquina!!!!", "Ganador", JOptionPane.INFORMATION_MESSAGE);
                    textIntentos.setText("0");
                    textInfo.setText("");
                    textApuesta.setText("");
                    numeroAleatorio = (int) ((Math.random() * 100) + 1);
                } else if (numJugador < numeroAleatorio) {
                    textInfo.setText("La apuesta es menor al numero pensado");
                    textIntentos.setText((Integer.parseInt(textIntentos.getText().toString()) + 1) + "");
                    textApuesta.setText("");
                } else if (numJugador > numeroAleatorio) {
                    textInfo.setText("La apuesta es mayor al numero pensado");
                    textIntentos.setText((Integer.parseInt(textIntentos.getText().toString()) + 1) + "");
                    textApuesta.setText("");
                }
            } else {
                textInfo.setText("La apuesta esta fuera de rango.");
                textIntentos.setText((Integer.parseInt(textIntentos.getText().toString()) + 1) + "");
                textApuesta.setText("");
            }
        } catch (NumberFormatException e) {
            textInfo.setText("Error. Hay que introducir un numero.");
            textIntentos.setText((Integer.parseInt(textIntentos.getText().toString()) + 1) + "");
            textApuesta.setText("");
        }
    }//GEN-LAST:event_botonApuestaActionPerformed

    private void botonRendirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRendirseActionPerformed
        // TODO add your handling code here:
        textInfo.setText("El numero pensado es: " + numeroAleatorio + ". Se ha vuelto a calcular otro numero. Buena suerte.");
        numeroAleatorio = (int) ((Math.random() * 100) + 1);
        textIntentos.setText("0");
        textApuesta.setText("");
    }//GEN-LAST:event_botonRendirseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApartadoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApartadoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApartadoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApartadoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApartadoA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonApuesta;
    private javax.swing.JButton botonRendirse;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAdvina;
    private javax.swing.JLabel labelApuestas;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelIntento;
    private javax.swing.JLabel labelSubAdivina;
    private javax.swing.JTextField textApuesta;
    private javax.swing.JTextField textInfo;
    private javax.swing.JTextField textIntentos;
    // End of variables declaration//GEN-END:variables
}
