package Clase;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class ChorriCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form ChorriCalculadora
     */
    public ChorriCalculadora() {
        initComponents();
        this.setLocationRelativeTo(null);//Centrada en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        LabelPrimerNumero = new javax.swing.JLabel();
        primerNumero = new javax.swing.JTextField();
        LabelPrimerNumero2 = new javax.swing.JLabel();
        segundoNumero = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();
        labelSuma = new javax.swing.JLabel();
        suma = new javax.swing.JTextField();
        labelResta = new javax.swing.JLabel();
        resta = new javax.swing.JTextField();
        labelMultiplicacion = new javax.swing.JLabel();
        multiplicacion = new javax.swing.JTextField();
        labelDivision = new javax.swing.JLabel();
        division = new javax.swing.JTextField();
        botonSalir = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 51, 255));
        Titulo.setText("CHORRI CALCULADORA");

        LabelPrimerNumero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LabelPrimerNumero.setText("Primer número");

        primerNumero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        LabelPrimerNumero2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LabelPrimerNumero2.setText("Segundo número");

        segundoNumero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        botonCalcular.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonCalcular.setText("CALCULAR");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        labelSuma.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelSuma.setText("SUMA");

        suma.setEditable(false);
        suma.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        labelResta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelResta.setText("RESTA");

        resta.setEditable(false);
        resta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        labelMultiplicacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelMultiplicacion.setText("MULTIPLICACIÓN");

        multiplicacion.setEditable(false);
        multiplicacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        labelDivision.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelDivision.setText("DIVISIÓN");

        division.setEditable(false);
        division.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        botonSalir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelPrimerNumero)
                            .addGap(39, 39, 39)
                            .addComponent(primerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelPrimerNumero2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(segundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSuma, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelResta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelMultiplicacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDivision, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resta)
                            .addComponent(multiplicacion)
                            .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrimerNumero)
                    .addComponent(primerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrimerNumero2))
                .addGap(47, 47, 47)
                .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSuma)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelResta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMultiplicacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDivision))
                .addGap(18, 18, 18)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        // TODO add your handling code here:
        int num1 = 0, num2 = 0;

        try {
            num1 = Integer.parseInt(primerNumero.getText());
            num2 = Integer.parseInt(segundoNumero.getText());

            suma.setForeground(Color.BLACK);
            suma.setText(String.valueOf(num1 + num2));
            resta.setForeground(Color.black);
            resta.setText(String.valueOf(num1 - num2));
            multiplicacion.setForeground(Color.BLACK);
            multiplicacion.setText(String.valueOf(num1 * num2));
            division.setForeground(Color.black);
            try {
                labelError.setText("");
                division.setText(String.valueOf(num1 / num2));
            } catch (ArithmeticException e) {
                labelError.setForeground(Color.red);
                labelError.setText("Error. No se puede dividir por 0");
                division.setText(String.valueOf(0));
            }
        } catch (NumberFormatException e) {
            labelError.setForeground(Color.red);
            labelError.setText("Error. No se puede calcular con cadenas.");
            suma.setForeground(Color.red);
            suma.setText("ERROR");
            resta.setForeground(Color.red);
            resta.setText("ERROR");
            multiplicacion.setForeground(Color.red);
            multiplicacion.setText("ERROR");
            division.setForeground(Color.red);
            division.setText("ERROR");
        }


    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChorriCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChorriCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChorriCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChorriCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChorriCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPrimerNumero;
    private javax.swing.JLabel LabelPrimerNumero2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField division;
    private javax.swing.JLabel labelDivision;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelMultiplicacion;
    private javax.swing.JLabel labelResta;
    private javax.swing.JLabel labelSuma;
    private javax.swing.JTextField multiplicacion;
    private javax.swing.JTextField primerNumero;
    private javax.swing.JTextField resta;
    private javax.swing.JTextField segundoNumero;
    private javax.swing.JTextField suma;
    // End of variables declaration//GEN-END:variables
}
