package Ejercicio144;

/**
 *
 * @author usuario
 */
public class ejercicio144 extends javax.swing.JFrame {

    private int num1, num2, op;

    /**
     * Creates new form ejercicio144
     */
    public ejercicio144() {
        op = -1;
        num1 = -1;
        num2 = -1;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNumero = new javax.swing.JTextField();
        GridLayout = new javax.swing.JPanel();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonC = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        botonDiv = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonMulti = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(600, 496));

        textNumero.setEditable(false);
        textNumero.setBackground(new java.awt.Color(255, 255, 255));
        textNumero.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textNumero.setForeground(new java.awt.Color(0, 0, 0));
        textNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textNumero.setText("0");
        getContentPane().add(textNumero, java.awt.BorderLayout.PAGE_START);

        GridLayout.setLayout(new java.awt.GridLayout(4, 4));

        boton7.setBackground(new java.awt.Color(255, 255, 255));
        boton7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton7.setForeground(new java.awt.Color(0, 0, 0));
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        GridLayout.add(boton7);

        boton8.setBackground(new java.awt.Color(255, 255, 255));
        boton8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton8.setForeground(new java.awt.Color(0, 0, 0));
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        GridLayout.add(boton8);

        boton9.setBackground(new java.awt.Color(255, 255, 255));
        boton9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton9.setForeground(new java.awt.Color(0, 0, 0));
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        GridLayout.add(boton9);

        botonC.setBackground(new java.awt.Color(255, 255, 255));
        botonC.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonC.setForeground(new java.awt.Color(0, 0, 0));
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        GridLayout.add(botonC);

        boton4.setBackground(new java.awt.Color(255, 255, 255));
        boton4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton4.setForeground(new java.awt.Color(0, 0, 0));
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        GridLayout.add(boton4);

        boton5.setBackground(new java.awt.Color(255, 255, 255));
        boton5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton5.setForeground(new java.awt.Color(0, 0, 0));
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        GridLayout.add(boton5);

        boton6.setBackground(new java.awt.Color(255, 255, 255));
        boton6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton6.setForeground(new java.awt.Color(0, 0, 0));
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        GridLayout.add(boton6);

        botonMas.setBackground(new java.awt.Color(255, 255, 255));
        botonMas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonMas.setForeground(new java.awt.Color(0, 0, 0));
        botonMas.setText("+");
        botonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasActionPerformed(evt);
            }
        });
        GridLayout.add(botonMas);

        boton1.setBackground(new java.awt.Color(255, 255, 255));
        boton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton1.setForeground(new java.awt.Color(0, 0, 0));
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        GridLayout.add(boton1);

        boton2.setBackground(new java.awt.Color(255, 255, 255));
        boton2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton2.setForeground(new java.awt.Color(0, 0, 0));
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        GridLayout.add(boton2);

        boton3.setBackground(new java.awt.Color(255, 255, 255));
        boton3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton3.setForeground(new java.awt.Color(0, 0, 0));
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        GridLayout.add(boton3);

        botonResta.setBackground(new java.awt.Color(255, 255, 255));
        botonResta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonResta.setForeground(new java.awt.Color(0, 0, 0));
        botonResta.setText("-");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        GridLayout.add(botonResta);

        botonDiv.setBackground(new java.awt.Color(255, 255, 255));
        botonDiv.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonDiv.setForeground(new java.awt.Color(0, 0, 0));
        botonDiv.setText("/");
        botonDiv.setToolTipText("");
        botonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivActionPerformed(evt);
            }
        });
        GridLayout.add(botonDiv);

        boton0.setBackground(new java.awt.Color(255, 255, 255));
        boton0.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        boton0.setForeground(new java.awt.Color(0, 0, 0));
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        GridLayout.add(boton0);

        botonMulti.setBackground(new java.awt.Color(255, 255, 255));
        botonMulti.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonMulti.setForeground(new java.awt.Color(0, 0, 0));
        botonMulti.setText("*");
        botonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiActionPerformed(evt);
            }
        });
        GridLayout.add(botonMulti);

        botonIgual.setBackground(new java.awt.Color(51, 51, 255));
        botonIgual.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonIgual.setForeground(new java.awt.Color(255, 255, 255));
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        GridLayout.add(botonIgual);

        getContentPane().add(GridLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("7");
        } else {
            textNumero.setText(textNumero.getText() + "7");
        }

    }//GEN-LAST:event_boton7ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("4");
        } else {
            textNumero.setText(textNumero.getText() + "4");
        }
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("8");
        } else {
            textNumero.setText(textNumero.getText() + "8");
        }
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("9");
        } else {
            textNumero.setText(textNumero.getText() + "9");
        }
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("5");
        } else {
            textNumero.setText(textNumero.getText() + "5");
        }
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("6");
        } else {
            textNumero.setText(textNumero.getText() + "6");
        }
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("1");
        } else {
            textNumero.setText(textNumero.getText() + "1");
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("2");
        } else {
            textNumero.setText(textNumero.getText() + "2");
        }
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
        if (textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText("3");
        } else {
            textNumero.setText(textNumero.getText() + "3");
        }
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        // TODO add your handling code here:
        if (!textNumero.getText().equalsIgnoreCase("0")) {
            textNumero.setText(textNumero.getText() + "0");
        }
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        // TODO add your handling code here:
        textNumero.setText("0");
    }//GEN-LAST:event_botonCActionPerformed

    private void botonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasActionPerformed
        // TODO add your handling code here:
        num1 = Integer.valueOf(textNumero.getText());
        textNumero.setText("0");
        op = 1;
    }//GEN-LAST:event_botonMasActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        // TODO add your handling code here:
        num2 = Integer.valueOf(textNumero.getText());
        switch (op) {
            case 1:
                //suma
                textNumero.setText(Integer.toString(num1 + num2));
                break;
            case 2:
                //resta
                textNumero.setText(Integer.toString(num1 - num2));
                break;
            case 3:
                //Multiplicacion
                textNumero.setText(Integer.toString(num1 * num2));
                break;
            case 4:
                //division
                try{
                    textNumero.setText(Integer.toString(num1 / num2));
                }catch(ArithmeticException e){
                    textNumero.setText("Error. Division por 0");
                }             
                break;
            default:
                textNumero.setText("ERROR");

        }
        op = -1;
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        // TODO add your handling code here:
        num1 = Integer.valueOf(textNumero.getText());
        textNumero.setText("0");
        op = 2;
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiActionPerformed
        // TODO add your handling code here:
        num1 = Integer.valueOf(textNumero.getText());
        textNumero.setText("0");
        op = 3;
    }//GEN-LAST:event_botonMultiActionPerformed

    private void botonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivActionPerformed
        // TODO add your handling code here:
        num1 = Integer.valueOf(textNumero.getText());
        textNumero.setText("0");
        op = 4;
    }//GEN-LAST:event_botonDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio144.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio144.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio144.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio144.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio144().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GridLayout;
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonDiv;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMulti;
    private javax.swing.JButton botonResta;
    private javax.swing.JTextField textNumero;
    // End of variables declaration//GEN-END:variables
}
