package Ejercicio146;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class ejercicio146 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio146
     */
    private Dimension originalSize;

    public ejercicio146() {
        initComponents();
        originalSize = Slider.getPreferredSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slider = new javax.swing.JSlider();
        BotonReinicio = new javax.swing.JButton();
        text = new javax.swing.JTextField();
        botonAcercaDE = new javax.swing.JButton();
        labelDificultad = new javax.swing.JLabel();
        desplegableDificultad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Slider.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SliderMouseReleased(evt);
            }
        });

        BotonReinicio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonReinicio.setText("Reinicio");
        BotonReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReinicioActionPerformed(evt);
            }
        });

        text.setEditable(false);
        text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        text.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botonAcercaDE.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        botonAcercaDE.setText("Acerca de");
        botonAcercaDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcercaDEActionPerformed(evt);
            }
        });

        labelDificultad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelDificultad.setText("Elija la dificultad:");

        desplegableDificultad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        desplegableDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        desplegableDificultad.setSelectedIndex(2);
        desplegableDificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableDificultadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(BotonReinicio)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDificultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desplegableDificultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAcercaDE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botonAcercaDE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(labelDificultad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desplegableDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonReinicio))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReinicioActionPerformed
        // TODO add your handling code here:
        text.setText("");
        Slider.setEnabled(true);
    }//GEN-LAST:event_BotonReinicioActionPerformed

    private void SliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderMouseReleased
        // TODO add your handling code here:
        Slider.setEnabled(false);
        if (Slider.getValue() == 50) {
            text.setText("Enhorabuena acertastes!!!!!!!!!!");
            text.setForeground(Color.red);
        } else if (Slider.getValue() >= 40 && Slider.getValue() <= 60) {
            text.setText("Has estado cerca, prueba otra vez");
            text.setForeground(Color.ORANGE);
        } else {
            text.setText(Integer.toString(Slider.getValue()));
            text.setForeground(Color.green);
            //final
        }
    }//GEN-LAST:event_SliderMouseReleased

    private void desplegableDificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableDificultadActionPerformed
        // TODO add your handling code here:
        if (Integer.valueOf(desplegableDificultad.getSelectedItem().toString()) == 1) {
            Slider.setEnabled(true);
            text.setText("");
            Dimension d = new Dimension((int) (originalSize.width * 0.1), Slider.getHeight());
            Slider.setSize(d);
        } else if (Integer.valueOf(desplegableDificultad.getSelectedItem().toString()) == 2) {
            Slider.setEnabled(true);
            text.setText("");
            Dimension d = new Dimension((int) (originalSize.width * 0.5), Slider.getHeight());
            Slider.setSize(d);
        } else {
            Slider.setEnabled(true);
            text.setText("");
            Dimension d = new Dimension(originalSize.width , Slider.getHeight());
            Slider.setSize(d);
        }
    }//GEN-LAST:event_desplegableDificultadActionPerformed

    private void botonAcercaDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcercaDEActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Pablo Jesús Calvente Ramírez", "Acerca de...", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_botonAcercaDEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio146.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio146.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio146.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio146.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio146().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonReinicio;
    private javax.swing.JSlider Slider;
    private javax.swing.JButton botonAcercaDE;
    private javax.swing.JComboBox<String> desplegableDificultad;
    private javax.swing.JLabel labelDificultad;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
