package ApartoB;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Jesús Calvente Ramírez & Victor Moreno Benítez
 */
public class apartadoB extends javax.swing.JFrame {

    /**
     * Creates new form apartadoB
     */
    private int contador;
    
    public apartadoB() {
        initComponents();
        this.setTitle("Bombillas");
        this.setLocationRelativeTo(null);
        b1.setBackground(Color.GRAY);
        b2.setBackground(Color.GRAY);
        b3.setBackground(Color.GRAY);
        b4.setBackground(Color.GRAY);
        b5.setBackground(Color.GRAY);
        b6.setBackground(Color.GRAY);
        contador = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonEmpezar = new javax.swing.JButton();
        b1 = new javax.swing.JToggleButton();
        b2 = new javax.swing.JToggleButton();
        b3 = new javax.swing.JToggleButton();
        b4 = new javax.swing.JToggleButton();
        b5 = new javax.swing.JToggleButton();
        b6 = new javax.swing.JToggleButton();
        labelIntentos = new javax.swing.JLabel();
        textIntentos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonEmpezar.setText("Volver a Empezar");
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        labelIntentos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelIntentos.setText("Numero de intentos:");

        textIntentos.setEditable(false);
        textIntentos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textIntentos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

        if (b2.isSelected()) {
            b2.setSelected(false);
            b2.setBackground(Color.GRAY);
        } else {
            b2.setSelected(true);
            b2.setBackground(Color.YELLOW);
        }
        if (b1.isSelected()) {
            b1.setSelected(false);
        } else {
            b1.setSelected(true);
        }
        suma();
        if (b1.isSelected() && b2.isSelected() && b3.isSelected() && b4.isSelected() && b5.isSelected() && b6.isSelected()) {
            JOptionPane.showMessageDialog(this, "Enhorabuena has ganado.", "Campeon", JOptionPane.INFORMATION_MESSAGE);
            botonEmpezarActionPerformed(evt);
            contador = 0;
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if (b1.isSelected()) {
            b1.setSelected(false);
            b1.setBackground(Color.GRAY);
        } else {
            b1.setSelected(true);
            b1.setBackground(Color.YELLOW);
        }
        if (b3.isSelected()) {
            b3.setSelected(false);
            b3.setBackground(Color.GRAY);
        } else {
            b3.setSelected(true);
            b3.setBackground(Color.YELLOW);
        }
        if (b2.isSelected()) {
            b2.setSelected(false);
        } else {
            b2.setSelected(true);
        }
        suma();
        if (b1.isSelected() && b2.isSelected() && b3.isSelected() && b4.isSelected() && b5.isSelected() && b6.isSelected()) {
            JOptionPane.showMessageDialog(this, "Enhorabuena has ganado.", "Campeon", JOptionPane.INFORMATION_MESSAGE);
            botonEmpezarActionPerformed(evt);
            contador = 0;
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if (b2.isSelected()) {
            b2.setSelected(false);
            b2.setBackground(Color.GRAY);
        } else {
            b2.setSelected(true);
            b2.setBackground(Color.YELLOW);
        }
        if (b4.isSelected()) {
            b4.setSelected(false);
            b4.setBackground(Color.GRAY);
        } else {
            b4.setSelected(true);
            b4.setBackground(Color.YELLOW);
        }
        if (b3.isSelected()) {
            b3.setSelected(false);
        } else {
            b3.setSelected(true);
        }
        suma();
        if (b1.isSelected() && b2.isSelected() && b3.isSelected() && b4.isSelected() && b5.isSelected() && b6.isSelected()) {
            JOptionPane.showMessageDialog(this, "Enhorabuena has ganado.", "Campeon", JOptionPane.INFORMATION_MESSAGE);
            botonEmpezarActionPerformed(evt);
            contador = 0;
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if (b3.isSelected()) {
            b3.setSelected(false);
            b3.setBackground(Color.GRAY);
        } else {
            b3.setSelected(true);
            b3.setBackground(Color.YELLOW);
        }
        if (b5.isSelected()) {
            b5.setSelected(false);
            b5.setBackground(Color.GRAY);
        } else {
            b5.setSelected(true);
            b5.setBackground(Color.YELLOW);
        }
        if (b4.isSelected()) {
            b4.setSelected(false);
        } else {
            b4.setSelected(true);
        }
        suma();
        if (b1.isSelected() && b2.isSelected() && b3.isSelected() && b4.isSelected() && b5.isSelected() && b6.isSelected()) {
            JOptionPane.showMessageDialog(this, "Enhorabuena has ganado.", "Campeon", JOptionPane.INFORMATION_MESSAGE);
            botonEmpezarActionPerformed(evt);
            contador = 0;
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if (b4.isSelected()) {
            b4.setSelected(false);
            b4.setBackground(Color.GRAY);
        } else {
            b4.setSelected(true);
            b4.setBackground(Color.YELLOW);
        }
        if (b6.isSelected()) {
            b6.setSelected(false);
            b6.setBackground(Color.GRAY);
        } else {
            b6.setSelected(true);
            b6.setBackground(Color.YELLOW);
        }
        if (b5.isSelected()) {
            b5.setSelected(false);
        } else {
            b5.setSelected(true);
        }
        suma();
        if (b1.isSelected() && b2.isSelected() && b3.isSelected() && b4.isSelected() && b5.isSelected() && b6.isSelected()) {
            JOptionPane.showMessageDialog(this, "Enhorabuena has ganado.", "Campeon", JOptionPane.INFORMATION_MESSAGE);
            botonEmpezarActionPerformed(evt);
            contador = 0;
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if (b5.isSelected()) {
            b5.setSelected(false);
            b5.setBackground(Color.GRAY);
        } else {
            b5.setSelected(true);
            b5.setBackground(Color.YELLOW);
        }
        if (b6.isSelected()) {
            b6.setSelected(false);
        } else {
            b6.setSelected(true);
        }
        suma();
        if (b1.isSelected() && b2.isSelected() && b3.isSelected() && b4.isSelected() && b5.isSelected() && b6.isSelected()) {
            JOptionPane.showMessageDialog(this, "Enhorabuena has ganado.", "Campeon", JOptionPane.INFORMATION_MESSAGE);
            botonEmpezarActionPerformed(evt);
            contador = 0;
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed
        // TODO add your handling code here:
        b1.setSelected(false);
        b1.setBackground(Color.GRAY);
        b2.setSelected(false);
        b2.setBackground(Color.GRAY);
        b3.setSelected(false);
        b3.setBackground(Color.GRAY);
        b4.setSelected(false);
        b4.setBackground(Color.GRAY);
        b5.setSelected(false);
        b5.setBackground(Color.GRAY);
        b6.setSelected(false);
        b6.setBackground(Color.GRAY);
        contador = 0;
        textIntentos.setText(Integer.toString(contador));
    }//GEN-LAST:event_botonEmpezarActionPerformed
    
    protected void suma() {
        contador++;
        textIntentos.setText(Integer.toString(contador));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apartadoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apartadoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apartadoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apartadoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apartadoB().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton b1;
    private javax.swing.JToggleButton b2;
    private javax.swing.JToggleButton b3;
    private javax.swing.JToggleButton b4;
    private javax.swing.JToggleButton b5;
    private javax.swing.JToggleButton b6;
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JLabel labelIntentos;
    private javax.swing.JTextField textIntentos;
    // End of variables declaration//GEN-END:variables
}
